"""add elo to player

Revision ID: 25b28ae08c21
Revises: 6436c1ab0155
Create Date: 2026-02-17 17:52:56.234711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b28ae08c21'
down_revision: Union[str, Sequence[str], None] = '6436c1ab0155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('elo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'elo')
    # ### end Alembic commands ###
